- name: setup ansible
  hosts: all

  vars:
    ansible_ssh_private_key_file: /home/ansible/.ssh/pve
    ansible_user: root
  
  tasks:
    - name: setup vars
      ansible.builtin.include_vars:
        file:  /home/ansible/ansible_vars/ansible_user_vars.yml
        name: usercreate
  
    - name: Create Ansible user
      ansible.builtin.user:
        name: ansible
        password: "{{usercreate.ansible_password | string |password_hash('sha512')}}"
        create_home: true
        shell: /bin/bash
        groups: sudo
    - name: setup ssh keys for ansible
      ansible.posix.authorized_key:
        user: ansible
        key: "{{ lookup('file', '/home/ansible/.ssh/ansible.pub') }}"